### PR TITLE
Added "random" option

### PR DESCRIPTION
**Pull request by 0dayCTF**
Added the option to randomly loop through advertising data.

### CODE REVIEW

**Comment by 0dayCTF** [comment]
I'm not sure if this is something you intentionally left out, if so I apologize. Also, please let me know if I can help in any way! Thank you for your work.

**Comment by liquidz00** [comment]
@0dayCTF huge fan of your work, thank **you** for all that you do

**Comment by 0dayCTF** [comment]
Thank you @liquidz00 I appreciate that!

**Comment by ECTO-1A** [comment]
Woah! Hey Ryan! Thanks so much! It's been on my to-do list for weeks to go back and add the random option so I really appreciate the help!

**Pull request merged**
