### PR TITLE
Option to advertise all devices

### PR DESCRIPTION
**Pull request by ReSo7200**
Adds the ability to adv all devices and switching them automatically or manually.

Cleans some of the code. (Devices bytes are in a new class in a new file now)

### CODE REVIEW

**Comment by innerfirebg** [comment]
> Adds the ability to adv all devices and switching them automatically or manually.
> 
> Cleans some of the code. (Devices bytes are in a new class in a new file now)

it's nice, but you can't stop this script when u use ctrl+c in auto mode...

**Comment by ReSo7200** [comment]
Ez ctrl + z would do it 😅

**Comment by liquidz00** [comment]
Holy `if..elif` statement batman 😂

**Comment by ECTO-1A** [comment]
cleaner method created.

**Pull request closed without merging**
